# Generated by Django 3.1.1 on 2020-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200913_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookrelation',
            name='discount',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
